INSERT INTO "moves" VALUES(1025,'catastropika',7,13,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1025, 9, "Catastropika");
INSERT INTO "move_flavor_text" VALUES(1025, 7, 9, "The user, Pikachu, surrounds itself with the\nmaximum amount of electricity using its Z-Power\nand pounces on its target with full force.");
INSERT INTO "moves" VALUES(1026,'shore-up',7,5,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1026, 9, "Shore Up");
INSERT INTO "move_flavor_text" VALUES(1026, 7, 9, "The user regains up to half of its max HP. It restores\nmore HP in a sandstorm.");
INSERT INTO "moves" VALUES(1027,'first-impression',7,7,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1027, 9, "First Impression");
INSERT INTO "move_flavor_text" VALUES(1027, 7, 9, "Although this move has great power, it only works\nthe first turn the user is in battle.");
INSERT INTO "moves" VALUES(1028,'baneful-bunker',7,4,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1028, 9, "Baneful Bunker");
INSERT INTO "move_flavor_text" VALUES(1028, 7, 9, "In addition to protecting the user from attacks, this\nmove also poisons any attacker that makes\ndirect contact.");
INSERT INTO "moves" VALUES(1029,'spirit-shackle',7,8,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1029, 9, "Spirit Shackle");
INSERT INTO "move_flavor_text" VALUES(1029, 7, 9, "The user attacks while simultaneously stitching the\ntarget’s shadow to the ground to prevent the target\nfrom escaping.");
INSERT INTO "moves" VALUES(1030,'darkest-lariat',7,17,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1030, 9, "Darkest Lariat");
INSERT INTO "move_flavor_text" VALUES(1030, 7, 9, "The user swings both arms and hits the target.\nThe target’s stat changes don’t affect this\nattack’s damage.");
INSERT INTO "moves" VALUES(1031,'sparkling-aria',7,11,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1031, 9, "Sparkling Aria");
INSERT INTO "move_flavor_text" VALUES(1031, 7, 9, "The user bursts into song, emitting many bubbles.\nAny Pokémon suffering from a burn will be healed\nby the touch of these bubbles.");
INSERT INTO "moves" VALUES(1032,'ice-hammer',7,15,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1032, 9, "Ice Hammer");
INSERT INTO "move_flavor_text" VALUES(1032, 7, 9, "The user swings and hits with its strong, heavy fist.\nIt lowers the user’s Speed, however.");
INSERT INTO "moves" VALUES(1033,'floral-healing',7,18,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1033, 9, "Floral Healing");
INSERT INTO "move_flavor_text" VALUES(1033, 7, 9, "The user restores the target’s HP by up to half of its\nmax HP. It restores more HP when the terrain\nis grass.");
INSERT INTO "moves" VALUES(1034,'high-horsepower',7,5,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1034, 9, "High Horsepower");
INSERT INTO "move_flavor_text" VALUES(1034, 7, 9, "The user fiercely attacks the target using its\nentire body.");
INSERT INTO "moves" VALUES(1035,'strength-sap',7,12,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1035, 9, "Strength Sap");
INSERT INTO "move_flavor_text" VALUES(1035, 7, 9, "The user restores its HP by the same amount as the\ntarget’s Attack stat. It also lowers the target’s\nAttack stat.");
INSERT INTO "moves" VALUES(1036,'solar-blade',7,12,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1036, 9, "Solar Blade");
INSERT INTO "move_flavor_text" VALUES(1036, 7, 9, "In this two-turn attack, the user gathers light and\nfills a blade with the light’s energy, attacking the\ntarget on the next turn.");
INSERT INTO "moves" VALUES(1037,'leafage',7,12,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1037, 9, "Leafage");
INSERT INTO "move_flavor_text" VALUES(1037, 7, 9, "The user attacks by pelting the target with leaves.");
INSERT INTO "moves" VALUES(1038,'spotlight',7,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1038, 9, "Spotlight");
INSERT INTO "move_flavor_text" VALUES(1038, 7, 9, "The user shines a spotlight on the target so that\nonly the target will be attacked during the turn.");
INSERT INTO "moves" VALUES(1039,'toxic-thread',7,4,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1039, 9, "Toxic Thread");
INSERT INTO "move_flavor_text" VALUES(1039, 7, 9, "The user shoots poisonous threads to poison the\ntarget and lower the target’s Speed stat.");
INSERT INTO "moves" VALUES(1040,'laser-focus',7,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1040, 9, "Laser Focus");
INSERT INTO "move_flavor_text" VALUES(1040, 7, 9, "The user concentrates intensely. The attack on the\nnext turn always results in a critical hit.");
INSERT INTO "moves" VALUES(1041,'gear-up',7,9,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1041, 9, "Gear Up");
INSERT INTO "move_flavor_text" VALUES(1041, 7, 9, "The user engages its gears to raise the Attack and\nSp. Atk stats of ally Pokémon with the Plus or\nMinus Ability.");
INSERT INTO "moves" VALUES(1042,'throat-chop',7,17,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1042, 9, "Throat Chop");
INSERT INTO "move_flavor_text" VALUES(1042, 7, 9, "The user attacks the target’s throat, and the\nresultant suffering prevents the target from using\nmoves that emit sound for two turns.");
INSERT INTO "moves" VALUES(1043,'pollen-puff',7,7,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1043, 9, "Pollen Puff");
INSERT INTO "move_flavor_text" VALUES(1043, 7, 9, "The user attacks the enemy with a pollen puff that\nexplodes. If the target is an ally, it gives the ally a\npollen puff that restores its HP instead.");
INSERT INTO "moves" VALUES(1044,'anchor-shot',7,9,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1044, 9, "Anchor Shot");
INSERT INTO "move_flavor_text" VALUES(1044, 7, 9, "The user entangles the target with its anchor chain\nwhile attacking. The target becomes unable to flee.");
INSERT INTO "moves" VALUES(1045,'psychic-terrain',7,14,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1045, 9, "Psychic Terrain");
INSERT INTO "move_flavor_text" VALUES(1045, 7, 9, "This protects Pokémon on the ground from priority\nmoves and powers up Psychic-type moves for\nfive turns.");
INSERT INTO "moves" VALUES(1046,'lunge',7,7,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1046, 9, "Lunge");
INSERT INTO "move_flavor_text" VALUES(1046, 7, 9, "The user makes a lunge at the target, attacking with\nfull force. This also lowers the target’s Attack stat.");
INSERT INTO "moves" VALUES(1047,'fire-lash',7,10,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1047, 9, "Fire Lash");
INSERT INTO "move_flavor_text" VALUES(1047, 7, 9, "The user strikes the target with a burning lash. This\nalso lowers the target’s Defense stat.");
INSERT INTO "moves" VALUES(1048,'power-trip',7,17,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1048, 9, "Power Trip");
INSERT INTO "move_flavor_text" VALUES(1048, 7, 9, "The user boasts its strength and attacks the target.\nThe more the user’s stats are raised, the greater the\nmove’s power.");
INSERT INTO "moves" VALUES(1049,'burn-up',7,10,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1049, 9, "Burn Up");
INSERT INTO "move_flavor_text" VALUES(1049, 7, 9, "To inflict massive damage, the user burns itself out.\nAfter using this move, the user will no longer be\nFire type.");
INSERT INTO "moves" VALUES(1050,'speed-swap',7,14,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1050, 9, "Speed Swap");
INSERT INTO "move_flavor_text" VALUES(1050, 7, 9, "The user exchanges Speed stats with the target.");
INSERT INTO "moves" VALUES(1051,'smart-strike',7,9,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1051, 9, "Smart Strike");
INSERT INTO "move_flavor_text" VALUES(1051, 7, 9, "The user stabs the target with a sharp horn. This\nattack never misses.");
INSERT INTO "moves" VALUES(1052,'purify',7,4,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1052, 9, "Purify");
INSERT INTO "move_flavor_text" VALUES(1052, 7, 9, "The user heals the target’s status condition. If the\nmove succeeds, it also restores the user’s own HP.");
INSERT INTO "moves" VALUES(1053,'revelation-dance',7,1,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1053, 9, "Revelation Dance");
INSERT INTO "move_flavor_text" VALUES(1053, 7, 9, "The user attacks the target by dancing very hard.\nThe user’s type determines the type of this move.");
INSERT INTO "moves" VALUES(1054,'core-enforcer',7,16,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1054, 9, "Core Enforcer");
INSERT INTO "move_flavor_text" VALUES(1054, 7, 9, "If the Pokémon the user has inflicted damage on\nhave already used their moves, this move eliminates\nthe effect of the target’s Ability.");
INSERT INTO "moves" VALUES(1055,'trop-kick',7,12,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1055, 9, "Trop Kick");
INSERT INTO "move_flavor_text" VALUES(1055, 7, 9, "The user lands an intense kick of tropical origins on\nthe target. This also lowers the target’s Attack stat.");
INSERT INTO "moves" VALUES(1056,'instruct',7,14,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1056, 9, "Instruct");
INSERT INTO "move_flavor_text" VALUES(1056, 7, 9, "The user instructs the target to use the target’s last\nmove again.");
INSERT INTO "moves" VALUES(1057,'beak-blast',7,3,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1057, 9, "Beak Blast");
INSERT INTO "move_flavor_text" VALUES(1057, 7, 9, "The user first heats up its beak, and then it attacks\nthe target. Making direct contact with the Pokémon\nwhile it’s heating up its beak results in a burn.");
INSERT INTO "moves" VALUES(1058,'clanging-scales',7,16,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1058, 9, "Clanging Scales");
INSERT INTO "move_flavor_text" VALUES(1058, 7, 9, "The user rubs the scales on its entire body and\nmakes a huge noise to attack the opposing Pokémon.\nThe user’s Defense stat goes down after the attack.");
INSERT INTO "moves" VALUES(1059,'dragon-hammer',7,16,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1059, 9, "Dragon Hammer");
INSERT INTO "move_flavor_text" VALUES(1059, 7, 9, "The user uses its body like a hammer to attack the\ntarget and inflict damage.");
INSERT INTO "moves" VALUES(1060,'brutal-swing',7,17,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1060, 9, "Brutal Swing");
INSERT INTO "move_flavor_text" VALUES(1060, 7, 9, "The user swings its body around violently to inflict\ndamage on everything in its vicinity.");
INSERT INTO "moves" VALUES(1061,'aurora-veil',7,15,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1061, 9, "Aurora Veil");
INSERT INTO "move_flavor_text" VALUES(1061, 7, 9, "This move reduces damage from physical and\nspecial moves for five turns. This can be used only\nin a hailstorm.");
INSERT INTO "moves" VALUES(1063,'malicious-moonsault',7,17,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1063, 9, "Malicious Moonsault");
INSERT INTO "move_flavor_text" VALUES(1063, 7, 9, "The user, Incineroar, strengthens its body using\nits Z-Power and crashes into the target with\nfull force.");
INSERT INTO "moves" VALUES(1065,'soul-stealing--star-strike',7,8,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1065, 9, "Soul-Stealing -Star Strike");
INSERT INTO "move_flavor_text" VALUES(1065, 7, 9, "After obtaining Z-Power, the user, Marshadow,\npunches and kicks the target consecutively\nwith full force.");
INSERT INTO "moves" VALUES(1066,'stoked-sparksurfer',7,13,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1066, 9, "Stoked Sparksurfer");
INSERT INTO "move_flavor_text" VALUES(1066, 7, 9, "After obtaining Z-Power, the user, Alolan Raichu,\nattacks the target with full force. This move leaves\nthe target with paralysis.");
INSERT INTO "moves" VALUES(1067,'pulverizing-pancake',7,1,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1067, 9, "Pulverizing Pancake");
INSERT INTO "move_flavor_text" VALUES(1067, 7, 9, "Z-Power brings out the true capabilities of the user,\nSnorlax. The Pokémon moves its enormous body\nenergetically and attacks the target with full force.");
INSERT INTO "moves" VALUES(1068,'genesis-supernova',7,14,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1068, 9, "Genesis Supernova");
INSERT INTO "move_flavor_text" VALUES(1068, 7, 9, "After obtaining Z-Power, the user, Mew, attacks\nthe target with full force. The terrain will be charged\nwith psychic energy.");
INSERT INTO "moves" VALUES(1069,'shell-trap',7,10,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1069, 9, "Shell Trap");
INSERT INTO "move_flavor_text" VALUES(1069, 7, 9, "The user sets a shell trap. If the user is hit by a\nphysical move, the trap will explode and inflict\ndamage on the opposing Pokémon.");
INSERT INTO "moves" VALUES(1070,'fleur-cannon',7,18,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1070, 9, "Fleur Cannon");
INSERT INTO "move_flavor_text" VALUES(1070, 7, 9, "The user unleashes a strong beam. The attack’s\nrecoil harshly lowers the user’s Sp. Atk stat.");
INSERT INTO "moves" VALUES(1071,'psychic-fangs',7,14,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1071, 9, "Psychic Fangs");
INSERT INTO "move_flavor_text" VALUES(1071, 7, 9, "The user bites the target with its psychic\ncapabilities. This can also destroy Light Screen\nand Reflect.");
INSERT INTO "moves" VALUES(1072,'stomping-tantrum',7,5,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1072, 9, "Stomping Tantrum");
INSERT INTO "move_flavor_text" VALUES(1072, 7, 9, "Driven by frustration, the user attacks the target. If\nthe user’s previous move has failed, the power of\nthis move doubles.");
INSERT INTO "moves" VALUES(1073,'shadow-bone',7,8,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1073, 9, "Shadow Bone");
INSERT INTO "move_flavor_text" VALUES(1073, 7, 9, "The user attacks by beating the target with a\nbone that contains a spirit. This may also lower\nthe target’s Defense stat.");
INSERT INTO "moves" VALUES(1074,'accelerock',7,6,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1074, 9, "Accelerock");
INSERT INTO "move_flavor_text" VALUES(1074, 7, 9, "The user smashes into the target at high speed.\nThis move always goes first.");
INSERT INTO "moves" VALUES(1075,'liquidation',7,11,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1075, 9, "Liquidation");
INSERT INTO "move_flavor_text" VALUES(1075, 7, 9, "The user slams into the target using a full-force\nblast of water. This may also lower the target’s\nDefense stat.");
INSERT INTO "moves" VALUES(1076,'prismatic-laser',7,14,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1076, 9, "Prismatic Laser");
INSERT INTO "move_flavor_text" VALUES(1076, 7, 9, "The user shoots powerful lasers using the power of\na prism. The user can’t move on the next turn.");
INSERT INTO "moves" VALUES(1077,'spectral-thief',7,8,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1077, 9, "Spectral Thief");
INSERT INTO "move_flavor_text" VALUES(1077, 7, 9, "The user hides in the target’s shadow, steals\nthe target’s stat boosts, and then attacks.");
INSERT INTO "moves" VALUES(1078,'sunsteel-strike',7,9,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1078, 9, "Sunsteel Strike");
INSERT INTO "move_flavor_text" VALUES(1078, 7, 9, "The user slams into the target with the force of a\nmeteor. This move can be used on the target \nregardless of its Abilities.");
INSERT INTO "moves" VALUES(1079,'moongeist-beam',7,8,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1079, 9, "Moongeist Beam");
INSERT INTO "move_flavor_text" VALUES(1079, 7, 9, "The user emits a sinister ray to attack the target.\nThis move can be used on the target regardless of \nits Abilities.");
INSERT INTO "moves" VALUES(1080,'tearful-look',7,1,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1080, 9, "Tearful Look");
INSERT INTO "move_flavor_text" VALUES(1080, 7, 9, "The user gets teary eyed to make the target lose\nits combative spirit. This lowers the target’s\nAttack and Sp. Atk stats.");
INSERT INTO "moves" VALUES(1081,'zing-zap',7,13,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1081, 9, "Zing Zap");
INSERT INTO "move_flavor_text" VALUES(1081, 7, 9, "A strong electric blast crashes down on the target,\ngiving it an electric shock. This may also make the\ntarget flinch.");
INSERT INTO "moves" VALUES(1082,'natures-madness',7,18,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1082, 9, "Natures Madness");
INSERT INTO "move_flavor_text" VALUES(1082, 7, 9, "The user hits the target with the force of nature.\nIt halves the target’s HP.");
INSERT INTO "moves" VALUES(1083,'multi-attack',7,1,NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1083, 9, "Multi-Attack");
INSERT INTO "move_flavor_text" VALUES(1083, 7, 9, "Cloaking itself in high energy, the user slams into the\ntarget. The memory held determines the move’s type.");
INSERT INTO "moves" VALUES(1084,'-volt-thunderbolt',7,13,NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "move_names" VALUES(1084, 9, " Volt Thunderbolt");
INSERT INTO "move_flavor_text" VALUES(1084, 7, 9, "The user, Pikachu wearing a cap, powers up a jolt of\nelectricity using its Z-Power and unleashes it.\nCritical hits land more easily.");
